name: Build on push to master

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        lfs: "true"
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate JavaDoc
      run: mvn -B javadoc:javadoc --file pom.xml
    - name: Commit build
      run: |
          git config --global user.name 'Github Action'
          git config --global user.email '<>'
          git add doc/javadoc/
          git commit -m "automated javadoc"
          git push
